name: Update

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add Git Commiter Details
      run: |
        git config --global user.email "sharunksplus@gmail.com"
        git config --global user.name "Sharun"

    - name: Upstream Setup & Merge
      run: |
        git remote add upstream https://github.com/SimplifyJobs/Summer2024-Internships.git
        git fetch upstream
        git merge --log upstream/dev --strategy=recursive --strategy-option=theirs

    # This has to be done first due to permissions reasons
    - name: Move other workflows
      run: |
        find .github/workflows/ -name '*.yml' ! -name 'update.yml' -exec git mv {} .github/archived-workflows/ \;

    - name: Commit and push
      run: |
        if [[ `git status --porcelain` ]]; then
          git commit -am "move unused workflows" && git push
        else
          echo "No changes to commit"
        fi


    - name: Update README.md
      run: |
        sed -i '/ðŸ”’/Id' README.md
        sed -i '/ðŸ‡ºðŸ‡¸/Id' README.md
        sed -i '/ðŸ›‚/Id' README.md
        sed -i '/Permanent Resident/Id' README.md
        sed -i '/citizens only/Id' README.md
        sed -i '/PhD/Id' README.md

    - name: Update README-Off-Season.md
      run: |
        sed -i '/ðŸ”’/Id' README-Off-Season.md
        sed -i '/ðŸ‡ºðŸ‡¸/Id' README-Off-Season.md
        sed -i '/ðŸ›‚/Id' README-Off-Season.md
        sed -i '/Permanent Resident/Id' README-Off-Season.md
        sed -i '/citizens only/Id' README-Off-Season.md
        sed -i '/PhD/Id' README-Off-Season.md

    - name: Commit
      run: |
        if [[ `git status --porcelain` ]]; then
          git commit -am "remove closed, no sponsorship entries and citizenship entries"
        else
          echo "No changes to commit"
        fi
        
    - name: Remove Fluff
      run: |
        sed -i '/Pitt CSC /,/The List/d' README.md
        sed -i '/Pitt CSC/,/The List/d' README-Off-Season.md
        sed -i '/Back to Top/,/Made with/d' README.md
        sed -i '/We love/,/Made with/d' README-Off-Season.md
        sed -i '/Jump to bottom/Id' README.md
        sed -i '/Jump to bottom/Id' README-Off-Season.md

    - name: Commit
      run: |
        if [[ `git status --porcelain` ]]; then
          git commit -am "remove fluff"
        else
          echo "No changes to commit"
        fi
        
    - name: Fix Links
      run: |
        sed -i 's|pittcsc/Summer2024-Internships/blob/dev/README|sharunkumar/Summer2024-Internships/blob/dev/README|g' README.md
        sed -i 's|pittcsc/Summer2024-Internships/blob/dev/README|sharunkumar/Summer2024-Internships/blob/dev/README|g' README-Off-Season.md
        sed -i 's|SimplifyJobs/Summer2024-Internships/blob/dev/README|sharunkumar/Summer2024-Internships/blob/dev/README|g' README.md
        sed -i 's|SimplifyJobs/Summer2024-Internships/blob/dev/README|sharunkumar/Summer2024-Internships/blob/dev/README|g' README-Off-Season.md

    - name: Commit
      run: |
        if [[ `git status --porcelain` ]]; then
          git commit -am "fixed links"
        else
          echo "No changes to commit"
        fi
        
    - name: Push
      run: git push
